services:
  client:
    build: ./client
    image: newmri/nyanspace-client:latest
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - server

  server:
    build: ./server
    image: newmri/nyanspace-server:latest
    environment:
      - MONGO_URI=mongodb://mongo:27017/nyanspace
      - REDIS_URI=redis://default:${REDIS_PASSWORD}@redis:6379
      - TZ=Asia/Seoul
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:8
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Seoul

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis-data:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Seoul

volumes:
  mongo-data:
  redis-data:
